import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "settings": 'Settings',
      "daily_promise": "Daily Promise",
      "picture": "Picture",
      "text": "Text",
      "type": "Type",
      "songs": "Songs",
      "q_and_a": "Q & A",
      "daily_manna": "Daily Manna",
      "enter_your_location": "Enter your location",
      'hello': 'Hello',
      'welcome': 'Welcome to our app',
      'home': 'Home',
      'read_bible': 'Read Bible',
      'dictionary': 'Dictionary',
      'prayer': 'Prayer',
      "today_reading": "Today's Reading",
      "continue_reading": "Continue reading",
      "posters": "Posters",
      "try": "Try",
      "encouragement": "Encouragement",
      "love": "Love",
      "emotion": "Emotion",
      "videos": "Videos",
      "see_all": "See all",
      "churches_nearby": "Churches nearby",
      "log_out": "Log out",
      "prayer_list": "Prayer List",
      "prayers": "Prayers",
      "notes": "Notes",
      "quizzes": "Quizzes",
      "reading_plan": "Reading Plan",
      "featured_dialogues": "Featured Dialogues",
      "holy_bible": "Holy Bible",
      "no_prayers_have_been_added_yet": "No prayers have been added yet",
      "add_a_prayer": "Add a prayer",
      "bible_learnings": "Bible Learnings",
      "lessons_from_the_scriptures_for_daily_living":
          "Lessons from the scriptures for daily living",
      "prayers_and_devotions": "Prayers and Devotions",
      "church_and_fellowship": "Church and Fellowship",
      "strengthen_your_faith_with_fellowship":
          "Strengthen your faith with fellowship.",
      "theme": "Theme",
      "language": "Language",
      "english": "English",
      "tamil": "Tamil",
      "dark_mode": "Dark Mode",
      "small": "Small",
      "medium": "Medium",
      "large": "Large",
      "extra_large": "Extra Large",
      "letter_size": "Letter Size",
      "letter_setting": "Letter Setting",
      "give_your_needs_to_the_lord": "Give your needs to the Lord.",
      "get_started": "Get started",
      "enter_a_title": "Enter a title",
      "submit": "Submit",
      "thank_you": "Thank you",
      "add_details_about_your_prayer": "Add details about your prayer",
      "thank_you_for_sending_a_prayer_request_we_are_praying_for_the_prayers_you_mentioned":
          "Thank you for sending a prayer request, we are praying for the prayers you mentioned.",
      "read_more": "Read more",
      "search": "Search",
      "current_location": "Current Location",
      "upon_the_rock_i_will_build_my_church": "Upon the rock I will build my church.",
      "find_out_now": "Find out now",
      "daily_prayers_and_spiritual_guidance":
          "Daily prayers and spiritual guidance.",
    },
    'ta_IN': {
      "settings": 'அமைப்புகள்',
      "daily_promise": "தினசரி வாக்குறுதி",
      "picture": "படம்",
      "text": "உரை",
      "type": "வகை",
      "songs": "பாடல்கள்",
      "q_and_a": "கேள்வி & பதில்",
      "daily_manna": "தினசரி மன்னா",
      "enter_your_location": "உங்கள் இருப்பிடத்தை உள்ளிடவும்",
      'hello': 'வணக்கம்',
      'welcome': 'எங்கள் பயன்பாட்டிற்கு வரவேற்கிறோம்',
      'home': 'முகப்பு',
      'read_bible': 'வேதாகமம் வாசி',
      'dictionary': 'அகராதி',
      'prayer': 'ஜெபம்',
      "today_reading": "இன்றைய வாசிப்பு",
      "continue_reading": "தொடர்ந்து படிக்க",
      "posters": "சுவரொட்டிகள்",
      "try": "முயற்சி",
      "encouragement": "ஊக்கம்",
      "love": "காதல்",
      "emotion": "உணர்ச்சி",
      "videos": "வீடியோக்கள்",
      "see_all": "அனைத்தையும் பார்க்கவும்",
      "churches_nearby": "அருகிலுள்ள தேவாலயங்கள்",
      "log_out": "வெளியேறு",
      "prayer_list": "பிரார்த்தனை பட்டியல்",
      "prayers": "பிரார்த்தனைகள்",
      "notes": "குறிப்புகள்",
      "quizzes": "வினாடி வினாக்கள்",
      "reading_plan": "வாசிப்பு திட்டம்",
      "featured_dialogues": "சிறப்பம்சமான வசனங்கல்",
      "holy_bible": "பரிசுத்த பைபிள்",
      "no_prayers_have_been_added_yet": "எந்த ஜெபமும் இதுவரை சேர்க்கப்படவில்ல",
      "add_a_prayer": "ஒரு பிரார்த்தனை சேர்க்க",
      "bible_learnings": "வேதத்தைக் கற்றறிதல்கள்",
      "lessons_from_the_scriptures_for_daily_living":
          "பைபிள் படிப்பதற்கான முக்கியமான பாடங்கள்",
      "prayers_and_devotions": "பிரார்த்தனைகள் மற்றும் பக்தி",
      "church_and_fellowship": "திருச்சபை மற்றும் உடன்பிறப்புகள்",
      "strengthen_your_faith_with_fellowship":
          "உங்கள் நம்பிக்கையை வலுப்படுத்தும் கற்றல்கள்.",
      "theme": "தீம்",
      "language": "மொழி",
      "english": "ஆங்கிலம்",
      "tamil": "தமிழ்",
      "dark_mode": "இரவு நிலை",
      "small": "சிறிய",
      "medium": "நடுத்தர",
      "large": "பெரியது",
      "letter_size": "எழுத்திரு அளவு",
      "letter_setting": "எழுத்திரு அமைப்புகள்",
      "extra_large": "கூடுதல் பெரியது",
      "give_your_needs_to_the_lord": "உங்கள் தேவைகளை ஆண்டவரிடம் கொடுக்கவும்",
      "get_started": "தொடங்குங்கள்",
      "enter_a_title": "தலைப்பை உள்ளிடவும்",
      "submit": "சமர்ப்பிக்கவும்",
      "read_more": "மேலும் படிக்க",
      "thank_you": "நன்றி",
      "search": "தேடு",
      "current_location": "தற்போதைய இடம்",
      "find_out_now": "இப்போது கண்டுபிடி",
      "upon_the_rock_i_will_build_my_church": "பாறையின் மீது நான் என் திருச்சபையை கட்டுவேன்",
      "thank_you_for_sending_a_prayer_request_we_are_praying_for_the_prayers_you_mentioned":
          "பிரார்த்தனை கோரிக்கையை அனுப்பியதற்கு நன்றி, நீங்கள் குறிப்பிட்ட பிராத்தைகளுக்காக நாங்கள் ஜெபிக்கிறோம்.",
      "add_details_about_your_prayer":
          "உங்கள் பிராத்தனை பற்றிய விவரங்களை சேர்க்கவும்",
      "daily_prayers_and_spiritual_guidance":
          "தினசரி பிரார்த்தனைகள் மற்றும் ஆன்மீக வழிகாட்டல்கள்.",
    },
  };
}
